import { useMemo, useState } from 'react'
import { Link, Route, Routes, useSearchParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronRight, Heart, Search, ShoppingBasket, Snowflake } from 'lucide-react'
import Navbar from './components/Navbar'
import RecipeCard from './components/RecipeCard'
import { recipes } from './data/recipes'
import { useLocalStorage } from './hooks/useLocalStorage'

function Home({ favorites, toggleFavorite }) {
  return <><section className="hero container"><div className="hero-copy"><p className="eyebrow">Еда, которая ждёт вас дома</p><h1>Готовим с любовью.<br/><i>Замораживаем</i> с умом.</h1><p className="hero-text">Простые рецепты, идеи для заготовок и спокойствие на всю неделю — в одном месте.</p><div className="hero-actions"><Link className="button primary" to="/recipes">Найти рецепт <ArrowRight size={18}/></Link><Link className="text-link" to="/freezing">Как замораживать <ChevronRight size={18}/></Link></div><div className="hero-proof"><span><b>100+</b> рецептов</span><span><b>0</b> стресса</span><span><b>7</b> дней заботы</span></div></div><div className="hero-visual"><div className="sun"></div><div className="plate">🥘</div><div className="leaf leaf-one">✦</div><div className="leaf leaf-two">✦</div><div className="note"><Snowflake size={19}/><span>Ужин уже<br/><b>готов!</b></span></div></div></section><section className="container section"><div className="section-heading"><div><p className="eyebrow">Начните здесь</p><h2>Вкусно сегодня,<br/>легко завтра</h2></div><p>Выберите то, что сейчас нужнее всего. Мы поможем сделать домашнюю еду простой привычкой.</p></div><div className="feature-grid"><Feature icon="❄️" title="Морозилка без мифов" text="Что замораживать, как хранить и как бережно размораживать." to="/freezing"/><Feature icon="🍽️" title="Меню на неделю" text="Соберите готовый план питания — от завтрака до ужина." to="/meal-prep"/><Feature icon="🛒" title="Список покупок" text="Ничего лишнего: продукты автоматически объединятся в список." to="/recipes"/></div></section><section className="warm-section"><div className="container"><div className="section-heading compact"><div><p className="eyebrow">Популярное</p><h2>Рецепты, к которым<br/>хочется возвращаться</h2></div><Link className="text-link" to="/recipes">Все рецепты <ArrowRight size={18}/></Link></div><div className="recipe-grid">{recipes.slice(0, 3).map(r => <RecipeCard key={r.id} recipe={r} isFavorite={favorites.includes(r.id)} onToggleFavorite={toggleFavorite}/>)}</div></div></section><section className="container quote"><div>“</div><p>Забота о себе не обязана занимать весь вечер. Иногда она начинается с контейнера супа в морозилке.</p><span>Морозилка с заботой</span></section></>
}
function Feature({ icon, title, text, to }) { return <Link to={to} className="feature"><span>{icon}</span><h3>{title}</h3><p>{text}</p><i><ArrowRight size={18}/></i></Link> }
function Recipes({ favorites, toggleFavorite }) { const [params] = useSearchParams(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Все'); const shown = useMemo(() => recipes.filter(r => (!params.get('favorites') || favorites.includes(r.id)) && (filter === 'Все' || r.category === filter) && `${r.title} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query, filter, favorites, params]); return <main className="container page"><p className="eyebrow">Коллекция рецептов</p><h1>Готовая еда —<br/><i>ваша опора</i></h1><div className="catalog-tools"><label><Search size={19}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Искать рецепт или ингредиент"/></label><div className="filters">{['Все', 'Завтрак', 'Обед', 'Ужин'].map(x => <button key={x} className={filter === x ? 'selected' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div></div><p className="result-count">{shown.length ? `Нашли ${shown.length} рецептов` : 'Пока ничего не нашли'}</p><div className="recipe-grid catalog">{shown.map(r => <RecipeCard key={r.id} recipe={r} isFavorite={favorites.includes(r.id)} onToggleFavorite={toggleFavorite}/>)}</div></main> }
function InfoPage({ type }) { const isFreeze = type === 'freezing'; return <main className="container page info-page"><p className="eyebrow">{isFreeze ? 'Без паники' : 'Планирование питания'}</p><h1>{isFreeze ? <>Морозилка —<br/><i>ваш союзник</i></> : <>Неделя, в которой<br/><i>есть время на себя</i></>}</h1><p className="lead">{isFreeze ? 'Заготовки экономят силы, а не лишают еду вкуса. Собрали основу, с которой легко начать.' : 'Собирайте любимые блюда в план, а список продуктов составится сам.'}</p><div className="info-cards">{(isFreeze ? [['1', 'Охладите блюдо', 'Не ставьте горячую еду в морозилку: дайте ей остыть до комнатной температуры.'], ['2', 'Подпишите контейнер', 'Название, дата и количество порций — три вещи, которые избавляют от сомнений.'], ['3', 'Размораживайте бережно', 'Переложите порцию в холодильник на ночь — так еда сохранит текстуру.']] : [['Пн', 'Куриные тефтели', 'Обед · 2 порции'], ['Ср', 'Тыквенный суп', 'Ужин · 2 порции'], ['Пт', 'Лазанья с индейкой', 'Ужин · 4 порции']]).map(([n,t,p]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p>{isFreeze && <Check size={20}/>}</article>)}</div></main> }
function Recipe({ favorites, toggleFavorite }) { const id = location.hash.split('/').pop(); const recipe = recipes.find(r => r.id === id) ?? recipes[0]; return <main className="container page recipe-page"><Link className="back" to="/recipes">← Все рецепты</Link><div className={`recipe-detail-art ${recipe.color}`}>{recipe.emoji}</div><div className="detail-copy"><p className="eyebrow">{recipe.category}</p><h1>{recipe.title}</h1><p className="lead">{recipe.description}</p><div className="detail-stats"><span>⏱ {recipe.prepTime + recipe.cookTime} мин</span><span>🍴 {recipe.servings} порции</span><span>🔥 {recipe.calories} ккал</span></div><button className="button primary" onClick={() => toggleFavorite(recipe.id)}><Heart size={18} fill={favorites.includes(recipe.id) ? 'currentColor' : 'none'}/>{favorites.includes(recipe.id) ? 'В избранном' : 'Сохранить рецепт'}</button></div><section className="recipe-content"><div><h2>Ингредиенты</h2><ul>{recipe.ingredients.map(item => <li key={item}>{item}</li>)}</ul></div><div><h2>Как приготовить</h2><ol>{recipe.steps.map(step => <li key={step}>{step}</li>)}</ol><p className="storage-tip"><Snowflake size={17}/> Для заморозки остудите блюдо, разложите порциями и подпишите дату. Хранить до {recipe.storage}.</p></div></section></main> }
function App(){ const [favorites, setFavorites] = useLocalStorage('morozilka-favorites', []); const toggleFavorite = id => setFavorites(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]); const props={favorites,toggleFavorite}; return <><Navbar favoritesCount={favorites.length}/><Routes><Route path="/" element={<Home {...props}/>}/><Route path="/recipes" element={<Recipes {...props}/>}/><Route path="/recipes/:id" element={<Recipe {...props}/>}/><Route path="/freezing" element={<InfoPage type="freezing"/>}/><Route path="/meal-prep" element={<InfoPage type="meal"/>}/></Routes><footer><div className="container"><span className="brand"><span className="brand-mark"><Snowflake size={18}/></span>Морозилка <b>с заботой</b></span><span>Домашняя еда. Меньше спешки. Больше тепла.</span></div></footer></> }
export default App
